# Generated by Django 5.1.7 on 2025-03-18 12:26

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "external_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField()),
            ],
            options={
                "verbose_name": "Thème",
                "verbose_name_plural": "Thèmes",
                "ordering": ("nom",),
            },
        ),
        migrations.CreateModel(
            name="Sujet",
            fields=[
                (
                    "external_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField()),
                ("themes", models.ManyToManyField(to="aides.theme")),
            ],
            options={
                "verbose_name": "Sujet",
                "verbose_name_plural": "Sujets",
                "ordering": ("nom",),
            },
        ),
        migrations.CreateModel(
            name="ZoneGeographique",
            fields=[
                (
                    "external_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField()),
                ("numero", models.CharField(blank=True, max_length=5)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Région", "Région"),
                            ("Département", "Département"),
                            ("Collectivité d'outre-mer", "Collectivité d'outre-mer"),
                            ("Collectivité sui generis", "Collectivité sui generis"),
                            ("Métropole", "Métropole"),
                            ("Communauté Urbaine", "Communauté Urbaine"),
                            ("Communauté d'Agglo", "Communauté d'Agglo"),
                            ("Communauté de communes", "Communauté de communes"),
                            ("Commune", "Commune"),
                        ]
                    ),
                ),
                ("code_postal", models.CharField(blank=True, max_length=5)),
                (
                    "epci",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membres",
                        to="aides.zonegeographique",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enfants",
                        to="aides.zonegeographique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone géographique",
                "verbose_name_plural": "Zones géographiques",
            },
        ),
        migrations.CreateModel(
            name="Operateur",
            fields=[
                (
                    "external_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField()),
                (
                    "zones_geographiques",
                    models.ManyToManyField(to="aides.zonegeographique"),
                ),
            ],
            options={
                "verbose_name": "Opérateur",
                "verbose_name_plural": "Opérateurs",
            },
        ),
        migrations.CreateModel(
            name="Aide",
            fields=[
                (
                    "external_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField()),
                (
                    "types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("Étude", "Étude"),
                                ("Formation", "Formation"),
                                ("Financement", "Financement"),
                                ("Avantage fiscal", "Avantage fiscal"),
                                ("Prêt", "Prêt"),
                                ("Remplacement", "Remplacement"),
                                ("Conseil", "Conseil"),
                                ("Audit", "Audit"),
                            ],
                            max_length=20,
                        ),
                        null=True,
                        size=None,
                    ),
                ),
                ("promesse", models.CharField(blank=True)),
                ("description_courte", models.TextField(blank=True)),
                ("description_longue", models.TextField(blank=True)),
                ("montant", models.CharField(blank=True)),
                ("lien", models.URLField(blank=True, max_length=2000)),
                ("date_debut", models.DateField(null=True)),
                ("date_fin", models.DateField(null=True)),
                ("effectif_min", models.PositiveIntegerField(null=True)),
                ("effectif_max", models.PositiveIntegerField(null=True)),
                (
                    "couverture_geographique",
                    models.CharField(
                        choices=[
                            ("National", "National"),
                            ("Régional", "Régional"),
                            ("France métropolitaine", "France métropolitaine"),
                            ("Outre-mer", "Outre-mer"),
                            ("Départemental", "Départemental"),
                            ("Local", "Local"),
                        ],
                        default="National",
                    ),
                ),
                (
                    "operateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aides.operateur",
                    ),
                ),
                (
                    "operateurs_secondaires",
                    models.ManyToManyField(
                        related_name="aides_secondaires", to="aides.operateur"
                    ),
                ),
                ("sujets", models.ManyToManyField(to="aides.sujet")),
                ("themes", models.ManyToManyField(to="aides.theme")),
                (
                    "zones_geographiques",
                    models.ManyToManyField(to="aides.zonegeographique"),
                ),
            ],
            options={
                "verbose_name": "Aide",
                "verbose_name_plural": "Aides",
                "required_db_vendor": "postgresql",
            },
        ),
    ]
