# Generated by Django 5.1.7 on 2025-03-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="nom",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="operateur",
            name="nom",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="sujet",
            name="nom",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="theme",
            name="nom",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="zonegeographique",
            name="nom",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
