# Generated by Django 5.1.7 on 2025-04-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0002_alter_aide_nom_alter_operateur_nom_alter_sujet_nom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sujet",
            name="nom_court",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="theme",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="theme",
            name="nom_court",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="nom",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="operateur",
            name="nom",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="sujet",
            name="nom",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="theme",
            name="nom",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="zonegeographique",
            name="nom",
            field=models.CharField(blank=True),
        ),
    ]
