# Generated by Django 5.2 on 2025-04-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0003_sujet_nom_court_theme_description_theme_nom_court_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "external_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(blank=True)),
                ("description", models.CharField(blank=True)),
            ],
            options={
                "verbose_name": "Type d'aides",
                "verbose_name_plural": "Types d'aides",
                "ordering": ("nom",),
            },
        ),
        migrations.RemoveField(
            model_name="aide",
            name="types",
        ),
        migrations.AddField(
            model_name="aide",
            name="types",
            field=models.ManyToManyField(to="aides.type"),
        ),
    ]
