# Generated by Django 5.2 on 2025-04-14 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0004_type_remove_aide_types_aide_types"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="operateur",
            new_name="organisme",
        ),
        migrations.AlterModelOptions(
            name="organisme",
            options={"verbose_name": "Organisme", "verbose_name_plural": "Organismes"},
        ),
        migrations.AddField(
            model_name="organisme",
            name="acronyme",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="operateur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aides.organisme",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="operateurs_secondaires",
            field=models.ManyToManyField(
                related_name="aides_secondaires", to="aides.organisme"
            ),
        ),
        migrations.RenameField(
            model_name="aide", old_name="operateur", new_name="organisme"
        ),
        migrations.RenameField(
            model_name="aide",
            old_name="operateurs_secondaires",
            new_name="organismes_secondaires",
        ),
    ]
