# Generated by Django 5.2 on 2025-04-14 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0005_organisme_alter_aide_operateur_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aide",
            name="themes",
        ),
    ]
