# Generated by Django 5.2 on 2025-04-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0006_remove_aide_themes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="theme",
            options={
                "ordering": ("-urgence", "nom"),
                "verbose_name": "Thème",
                "verbose_name_plural": "Thèmes",
            },
        ),
        migrations.AddField(
            model_name="theme",
            name="urgence",
            field=models.BooleanField(default=False),
        ),
    ]
