# Generated by Django 5.2 on 2025-04-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0007_alter_theme_options_theme_urgence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sujet",
            options={"verbose_name": "Sujet", "verbose_name_plural": "Sujets"},
        ),
        migrations.AlterModelOptions(
            name="theme",
            options={"verbose_name": "Thème", "verbose_name_plural": "Thèmes"},
        ),
        migrations.AlterField(
            model_name="aide",
            name="sujets",
            field=models.ManyToManyField(related_name="aides", to="aides.sujet"),
        ),
        migrations.AlterField(
            model_name="aide",
            name="types",
            field=models.ManyToManyField(related_name="aides", to="aides.type"),
        ),
        migrations.AlterField(
            model_name="aide",
            name="zones_geographiques",
            field=models.ManyToManyField(
                related_name="aides", to="aides.zonegeographique"
            ),
        ),
        migrations.AlterField(
            model_name="sujet",
            name="themes",
            field=models.ManyToManyField(related_name="sujets", to="aides.theme"),
        ),
    ]
