# Generated by Django 5.2 on 2025-04-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0008_alter_sujet_options_alter_theme_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aide",
            old_name="description_courte",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="aide",
            old_name="lien",
            new_name="url_demarche",
        ),
        migrations.RemoveField(
            model_name="aide",
            name="description_longue",
        ),
        migrations.AddField(
            model_name="aide",
            name="conditions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="aide",
            name="slug",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="aide",
            name="url_descriptif",
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
