# Generated by Django 5.2 on 2025-04-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0009_rename_description_courte_aide_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "external_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(blank=True)),
            ],
            options={
                "verbose_name": "Programme d'aides",
                "verbose_name_plural": "Programmes d'aides",
                "ordering": ("nom",),
            },
        ),
        migrations.AddField(
            model_name="aide",
            name="aap_ami",
            field=models.BooleanField(
                default=False, verbose_name="Appel à projet ou manifestation d'intérêt"
            ),
        ),
        migrations.AddField(
            model_name="aide",
            name="programmes",
            field=models.ManyToManyField(related_name="aides", to="aides.programme"),
        ),
    ]
