# Generated by Django 5.2 on 2025-04-29 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0010_filiere_groupementproducteurs_programme_aide_aap_ami_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filiere",
            fields=[
                (
                    "external_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(blank=True, max_length=100)),
                ("position", models.IntegerField(default=0, unique=True)),
                ("code_naf", models.CharField(blank=True, max_length=10)),
            ],
            options={
                "verbose_name": "Filière",
                "verbose_name_plural": "Filières",
                "ordering": ("position",),
            },
        ),
        migrations.CreateModel(
            name="GroupementProducteurs",
            fields=[
                (
                    "external_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(blank=True, max_length=100)),
                ("libelle", models.CharField(blank=True, max_length=200)),
                (
                    "is_real",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(libelle="", then=False),
                            default=True,
                            output_field=models.BooleanField(),
                        ),
                        output_field=models.BooleanField(),
                    ),
                ),
            ],
            options={
                "verbose_name": "Groupement de producteurs",
                "verbose_name_plural": "Groupement de producteurs",
                "ordering": ("-is_real", "nom"),
            },
        ),
        migrations.CreateModel(
            name="SousFiliere",
            fields=[
                (
                    "external_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(blank=True, max_length=100)),
                (
                    "filiere",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aides.filiere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous-filière",
                "verbose_name_plural": "Sous-filières",
            },
        ),
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "external_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(blank=True, max_length=100)),
                (
                    "sous_filiere",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aides.sousfiliere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Détail de production",
                "verbose_name_plural": "Détails de production",
            },
        ),
    ]
