# Generated by Django 5.2.1 on 2025-05-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0011_filiere_groupementproducteurs_sousfiliere_production"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisme",
            name="logo",
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name="organisme",
            name="logo_filename",
            field=models.CharField(blank=True),
        ),
    ]
