# Generated by Django 5.2.1 on 2025-05-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0012_organisme_logo_organisme_logo_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisme",
            name="logo_filename",
            field=models.CharField(blank=True, null=True),
        ),
    ]
