# Generated by Django 5.2.1 on 2025-05-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0013_alter_organisme_logo_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="slug",
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
