# Generated by Django 5.2.1 on 2025-05-20 13:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0014_alter_aide_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aide",
            old_name="effectif_max",
            new_name="eligibilite_effectif_max",
        ),
        migrations.RenameField(
            model_name="aide",
            old_name="effectif_min",
            new_name="eligibilite_effectif_min",
        ),
        migrations.AddField(
            model_name="aide",
            name="beneficiaires",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Agriculteurs", "Agri"),
                        ("CUMA", "Cuma"),
                        ("SICA", "Sica"),
                        ("SCA", "Sca"),
                        ("GIEE", "Giee"),
                        ("Organisations de producteurs", "Op"),
                    ]
                ),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="aide",
            name="contact",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="aide",
            name="duree_accompagnement",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="aide",
            name="eligibilite_age",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="aide",
            name="eligibilite_etape_avancement_projet",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Réflexion / Conception", "Conception"),
                        ("Mise en œuvre / Réalisation", "Realisation"),
                        ("Usage / Valorisation", "Usage"),
                    ]
                ),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="aide",
            name="etapes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="aide",
            name="exemple_projet",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="aide",
            name="filieres",
            field=models.ManyToManyField(to="aides.filiere"),
        ),
        migrations.AddField(
            model_name="aide",
            name="participation_agriculteur",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="aide",
            name="recurrence_aide",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Permanente", "Permanente"),
                    ("Ponctuelle", "Ponctuelle"),
                    ("Récurrente", "Recurrente"),
                    ("Annuelle", "Annuelle"),
                ],
            ),
        ),
        migrations.AddField(
            model_name="aide",
            name="type_depense",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="slug",
            field=models.CharField(blank=True, max_length=2000, unique=True),
        ),
    ]
