# Generated by Django 5.2.1 on 2025-06-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0015_rename_effectif_max_aide_eligibilite_effectif_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sujet",
            name="published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="theme",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
