# Generated by Django 5.2.2 on 2025-06-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0016_sujet_published_theme_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
