# Generated by Django 5.2.3 on 2025-06-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0017_aide_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="icon_name",
            field=models.CharField(blank=True),
        ),
    ]
