# Generated by Django 5.2.3 on 2025-06-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0018_type_icon_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="urgence",
            field=models.BooleanField(default=False),
        ),
    ]
