# Generated by Django 5.2.3 on 2025-06-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0020_alter_type_options_aide_eligibilite_cumulable"),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="last_published_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
