# Generated by Django 5.2.3 on 2025-06-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0021_aide_last_published_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aide",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="filiere",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="groupementproducteurs",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="organisme",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="production",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="programme",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="sousfiliere",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="sujet",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="type",
            name="external_id",
        ),
        migrations.AddField(
            model_name="aide",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="filiere",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="groupementproducteurs",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="organisme",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="production",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="sousfiliere",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="sujet",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="type",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.RemoveField(
            model_name="zonegeographique",
            name="external_id",
        ),
        migrations.AddField(
            model_name="zonegeographique",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
