# Generated by Django 5.2.3 on 2025-06-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0022_no_more_grist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="zonegeographique",
            old_name="numero",
            new_name="code",
        ),
        migrations.AlterField(
            model_name="zonegeographique",
            name="code",
            field=models.CharField(blank=True),
        ),
    ]
