# Generated by Django 5.2.3 on 2025-06-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0023_remove_zonegeographique_numero_zonegeographique_code"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="zonegeographique",
            unique_together={("type", "code")},
        ),
        migrations.AlterField(
            model_name="zonegeographique",
            name="type",
            field=models.CharField(
                choices=[
                    ("01 Région", "Région"),
                    ("03 Département", "Département"),
                    ("02 Collectivité d'outre-mer", "Collectivité d'outre-mer"),
                    ("04 EPCI", "EPCI"),
                    ("05 Commune", "Commune"),
                ]
            ),
        ),
        migrations.AlterModelOptions(
            name="zonegeographique",
            options={
                "ordering": ("type", "code"),
                "verbose_name": "Zone géographique",
                "verbose_name_plural": "Zones géographiques",
            },
        ),
    ]
