# Generated by Django 5.2.3 on 2025-06-25 14:52

from django.contrib.postgres.fields.hstore import HStoreField
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0024_alter_zonegeographique_type"),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name="aide",
            name="raw_data",
            field=HStoreField(null=True),
        ),
    ]
