# Generated by Django 5.2.3 on 2025-06-26 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0025_auto_20250625_1652"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="production",
            options={
                "verbose_name": "Détail de production",
                "verbose_name_plural": "Filières > Sous-filières > Détails de production",
            },
        ),
        migrations.AlterModelOptions(
            name="sousfiliere",
            options={
                "verbose_name": "Sous-filière",
                "verbose_name_plural": "Filières > Sous-filières",
            },
        ),
    ]
