# Generated by Django 5.2.3 on 2025-06-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0026_alter_production_options_alter_sousfiliere_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisme",
            name="zones_geographiques",
            field=models.ManyToManyField(blank=True, to="aides.zonegeographique"),
        ),
    ]
