# Generated by Django 5.2.3 on 2025-06-26 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0027_alter_organisme_zones_geographiques"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupementproducteurs",
            options={
                "ordering": ("nom",),
                "verbose_name": "Groupement de producteurs",
                "verbose_name_plural": "Groupement de producteurs",
            },
        ),
        migrations.RemoveField(
            model_name="groupementproducteurs",
            name="is_real",
        ),
    ]
