# Generated by Django 5.2.3 on 2025-06-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0028_alter_groupementproducteurs_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aide",
            name="published",
        ),
        migrations.AlterField(
            model_name="aide",
            name="slug",
            field=models.SlugField(max_length=2000),
        ),
        migrations.AddField(
            model_name="aide",
            name="status",
            field=models.CharField(
                choices=[
                    ("01 À traiter", "01 À traiter"),
                    ("02 À relire", "02 À relire"),
                    ("03 Publiée", "03 Publiée"),
                    ("04 Dépubliée", "04 Dépubliée"),
                ],
                default="01 À traiter",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aide",
            unique_together={("organisme", "nom")},
        ),
    ]
