# Generated by Django 5.2.3 on 2025-06-26 13:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0029_remove_aide_published_aide_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="zones_geographiques",
            field=models.ManyToManyField(
                blank=True, related_name="aides", to="aides.zonegeographique"
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="beneficiaires",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Agriculteurs", "Agri"),
                        ("CUMA", "Cuma"),
                        ("SICA", "Sica"),
                        ("SCA", "Sca"),
                        ("GIEE", "Giee"),
                        ("Organisations de producteurs", "Op"),
                    ]
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="couverture_geographique",
            field=models.CharField(
                blank=True,
                choices=[
                    ("National", "National"),
                    ("Régional", "Régional"),
                    ("France métropolitaine", "France métropolitaine"),
                    ("Outre-mer", "Outre-mer"),
                    ("Départemental", "Départemental"),
                    ("Local", "Local"),
                ],
                default="National",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="date_debut",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="date_fin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="eligibilite_effectif_max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="eligibilite_effectif_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="eligibilite_etape_avancement_projet",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Réflexion / Conception", "Conception"),
                        ("Mise en œuvre / Réalisation", "Realisation"),
                        ("Usage / Valorisation", "Usage"),
                    ]
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="filieres",
            field=models.ManyToManyField(blank=True, to="aides.filiere"),
        ),
        migrations.AlterField(
            model_name="aide",
            name="organisme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aides.organisme",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="organismes_secondaires",
            field=models.ManyToManyField(
                blank=True, related_name="aides_secondaires", to="aides.organisme"
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="programmes",
            field=models.ManyToManyField(
                blank=True, related_name="aides", to="aides.programme"
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="raw_data",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="organisme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aides.organisme",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="sujets",
            field=models.ManyToManyField(
                blank=True, related_name="aides", to="aides.sujet"
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="types",
            field=models.ManyToManyField(
                blank=True, related_name="aides", to="aides.type"
            ),
        ),
    ]
