# Generated by Django 5.2.3 on 2025-07-02 12:11

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0030_alter_aide_beneficiaires_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filiere",
            name="published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organisme",
            name="courriel",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="organisme",
            name="famille",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Opérateur", "Opérateur"),
                    ("Collectivité", "Collectivité"),
                    ("État", "État"),
                    ("UE", "UE"),
                    ("GAL", "GAL"),
                    ("Chambre consulaire", "Chambre consulaire"),
                    ("Interprofessions", "Interprofessions"),
                    ("Mixte", "Mixte"),
                ],
            ),
        ),
        migrations.AddField(
            model_name="organisme",
            name="secteurs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("Finance, économie", "Finance, économie"),
                        ("Agriculture", "Agriculture"),
                        ("Environnement", "Environnement"),
                        ("Emploi", "Emploi"),
                        ("Enseignement, formation", "Enseignement, formation"),
                        ("Tous", "Tous"),
                    ],
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="organisme",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="filieres",
            field=models.ManyToManyField(
                blank=True, related_name="aides", to="aides.filiere"
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="organisme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aides",
                to="aides.organisme",
            ),
        ),
        migrations.AlterField(
            model_name="filiere",
            name="position",
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name="organisme",
            name="logo_filename",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="zonegeographique",
            name="type",
            field=models.CharField(
                choices=[
                    ("01 Région", "Région"),
                    ("03 Département", "Département"),
                    ("02 Collectivité d’outre-mer", "Collectivité d'outre-mer"),
                    ("04 EPCI", "EPCI"),
                    ("05 Commune", "Commune"),
                ]
            ),
        ),
    ]
