# Generated by Django 5.2.3 on 2025-07-08 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0031_filiere_published_organisme_courriel_and_more"),
    ]

    operations = []
