# Generated by Django 5.2.4 on 2025-07-09 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0032_alter_aide_conditions_alter_aide_contact_and_more"),
    ]

    operations = []
