# Generated by Django 5.2.4 on 2025-07-10 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0033_alter_aide_conditions_alter_aide_contact_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="aide",
            unique_together=set(),
        ),
    ]
