# Generated by Django 5.2.4 on 2025-07-10 11:31

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0034_alter_aide_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="beneficiaires",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Agriculteurs", "Agri"),
                        ("CUMA", "Cuma"),
                        ("SICA", "Sica"),
                        ("SCA", "Sca"),
                        ("GIEE", "Giee"),
                        ("Organisations de producteurs", "Op"),
                    ]
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Bénéficiaires",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="couverture_geographique",
            field=models.CharField(
                choices=[
                    ("National", "National"),
                    ("Régional", "Régional"),
                    ("France métropolitaine", "France métropolitaine"),
                    ("Outre-mer", "Outre-mer"),
                    ("Départemental", "Départemental"),
                    ("Local", "Local"),
                ],
                default="National",
                verbose_name="Couverture géographique",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="date_debut",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date d’ouverture"
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="date_fin",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de clôture"
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="duree_accompagnement",
            field=models.CharField(
                blank=True, verbose_name="Durée de l’accompagnement"
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="eligibilite_effectif_max",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Éligibilité\xa0: effectif salarié maximum",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="eligibilite_effectif_min",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Éligibilité\xa0: effectif salarié minimum",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="eligibilite_etape_avancement_projet",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Réflexion / Conception", "Conception"),
                        ("Mise en œuvre / Réalisation", "Realisation"),
                        ("Usage / Valorisation", "Usage"),
                    ]
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Éligibilité\xa0: étape d’avancement du projet",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="filieres",
            field=models.ManyToManyField(
                blank=True,
                related_name="aides",
                to="aides.filiere",
                verbose_name="Filières",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="last_published_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="aide",
            name="nom",
            field=models.CharField(verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="aide",
            name="organisme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aides",
                to="aides.organisme",
                verbose_name="Organisme porteur",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="organismes_secondaires",
            field=models.ManyToManyField(
                blank=True,
                related_name="aides_secondaires",
                to="aides.organisme",
                verbose_name="Organismes porteurs secondaires",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="programmes",
            field=models.ManyToManyField(
                blank=True,
                related_name="aides",
                to="aides.programme",
                verbose_name="Programmes",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="promesse",
            field=models.CharField(blank=True, verbose_name="Promesse"),
        ),
        migrations.AlterField(
            model_name="aide",
            name="raw_data",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True,
                null=True,
                verbose_name="Données brutes issues de l’intégration",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="recurrence_aide",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Permanente", "Permanente"),
                    ("Ponctuelle", "Ponctuelle"),
                    ("Récurrente", "Recurrente"),
                    ("Annuelle", "Annuelle"),
                ],
                verbose_name="Récurrence",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="slug",
            field=models.SlugField(max_length=2000, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="aide",
            name="status",
            field=models.CharField(
                choices=[
                    ("01 À traiter", "01 À traiter"),
                    ("02 À relire", "02 À relire"),
                    ("03 Publiée", "03 Publiée"),
                    ("04 Dépubliée", "04 Dépubliée"),
                ],
                default="01 À traiter",
                verbose_name="État",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="sujets",
            field=models.ManyToManyField(
                blank=True,
                related_name="aides",
                to="aides.sujet",
                verbose_name="Sujets",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="types",
            field=models.ManyToManyField(
                blank=True,
                related_name="aides",
                to="aides.type",
                verbose_name="Types d’aides",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="url_demarche",
            field=models.URLField(
                blank=True, max_length=2000, verbose_name="Lien vers la démarche"
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="url_descriptif",
            field=models.URLField(
                blank=True, max_length=2000, verbose_name="Lien vers le descriptif"
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="zones_geographiques",
            field=models.ManyToManyField(
                blank=True,
                related_name="aides",
                to="aides.zonegeographique",
                verbose_name="Zones géographiques",
            ),
        ),
        migrations.AlterField(
            model_name="filiere",
            name="code_naf",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Code NAF associé"
            ),
        ),
        migrations.AlterField(
            model_name="filiere",
            name="nom",
            field=models.CharField(max_length=100, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="filiere",
            name="position",
            field=models.IntegerField(default=99, verbose_name="Position pour le tri"),
        ),
        migrations.AlterField(
            model_name="filiere",
            name="published",
            field=models.BooleanField(default=False, verbose_name="Publié"),
        ),
        migrations.AlterField(
            model_name="groupementproducteurs",
            name="libelle",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nom complet ou explication"
            ),
        ),
        migrations.AlterField(
            model_name="groupementproducteurs",
            name="nom",
            field=models.CharField(max_length=100, verbose_name="Nom court"),
        ),
        migrations.AlterField(
            model_name="organisme",
            name="acronyme",
            field=models.CharField(blank=True, verbose_name="Acronyme"),
        ),
        migrations.AlterField(
            model_name="organisme",
            name="courriel",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Adresse courriel"
            ),
        ),
        migrations.AlterField(
            model_name="organisme",
            name="famille",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Opérateur", "Opérateur"),
                    ("Collectivité", "Collectivité"),
                    ("État", "État"),
                    ("UE", "UE"),
                    ("GAL", "GAL"),
                    ("Chambre consulaire", "Chambre consulaire"),
                    ("Interprofessions", "Interprofessions"),
                    ("Mixte", "Mixte"),
                ],
                verbose_name="Famille",
            ),
        ),
        migrations.AlterField(
            model_name="organisme",
            name="logo",
            field=models.BinaryField(blank=True, verbose_name="Logo"),
        ),
        migrations.AlterField(
            model_name="organisme",
            name="nom",
            field=models.CharField(verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="organisme",
            name="secteurs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("Finance, économie", "Finance, économie"),
                        ("Agriculture", "Agriculture"),
                        ("Environnement", "Environnement"),
                        ("Emploi", "Emploi"),
                        ("Enseignement, formation", "Enseignement, formation"),
                        ("Tous", "Tous"),
                    ],
                ),
                blank=True,
                null=True,
                size=None,
                verbose_name="Secteurs",
            ),
        ),
        migrations.AlterField(
            model_name="organisme",
            name="url",
            field=models.URLField(blank=True, verbose_name="Lien"),
        ),
        migrations.AlterField(
            model_name="organisme",
            name="zones_geographiques",
            field=models.ManyToManyField(
                blank=True,
                to="aides.zonegeographique",
                verbose_name="Zones géographiques",
            ),
        ),
        migrations.AlterField(
            model_name="production",
            name="nom",
            field=models.CharField(max_length=100, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="production",
            name="sous_filiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="aides.sousfiliere"
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="nom",
            field=models.CharField(blank=True, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="sousfiliere",
            name="filiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="aides.filiere",
                verbose_name="Filière",
            ),
        ),
        migrations.AlterField(
            model_name="sousfiliere",
            name="nom",
            field=models.CharField(max_length=100, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="sujet",
            name="nom",
            field=models.CharField(verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="sujet",
            name="nom_court",
            field=models.CharField(verbose_name="Nom court"),
        ),
        migrations.AlterField(
            model_name="sujet",
            name="published",
            field=models.BooleanField(default=False, verbose_name="Publié"),
        ),
        migrations.AlterField(
            model_name="sujet",
            name="themes",
            field=models.ManyToManyField(
                related_name="sujets", to="aides.theme", verbose_name="Thèmes"
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="nom",
            field=models.CharField(verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="nom_court",
            field=models.CharField(verbose_name="Nom court"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="published",
            field=models.BooleanField(default=False, verbose_name="Publié"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="urgence",
            field=models.BooleanField(default=False, verbose_name="Urgence"),
        ),
        migrations.AlterField(
            model_name="type",
            name="description",
            field=models.CharField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="type",
            name="icon_name",
            field=models.CharField(
                blank=True, verbose_name="(technique) Nom de l’icône"
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="nom",
            field=models.CharField(verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="type",
            name="urgence",
            field=models.BooleanField(default=False, verbose_name="Urgence"),
        ),
        migrations.AlterField(
            model_name="zonegeographique",
            name="code",
            field=models.CharField(blank=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="zonegeographique",
            name="code_postal",
            field=models.CharField(
                blank=True, max_length=5, verbose_name="Code postal"
            ),
        ),
        migrations.AlterField(
            model_name="zonegeographique",
            name="epci",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membres",
                to="aides.zonegeographique",
                verbose_name="EPCI",
            ),
        ),
        migrations.AlterField(
            model_name="zonegeographique",
            name="nom",
            field=models.CharField(verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="zonegeographique",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enfants",
                to="aides.zonegeographique",
                verbose_name="Zone géographique parente (département ou région)",
            ),
        ),
        migrations.AlterField(
            model_name="zonegeographique",
            name="type",
            field=models.CharField(
                choices=[
                    ("01 Région", "Région"),
                    ("03 Département", "Département"),
                    ("02 Collectivité d’outre-mer", "Collectivité d'outre-mer"),
                    ("04 EPCI", "EPCI"),
                    ("05 Commune", "Commune"),
                ],
                verbose_name="Type",
            ),
        ),
    ]
