# Generated by Django 5.2.4 on 2025-07-10 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("aides", "0036_aide_date_created_aide_date_modified_and_more"),
        ("aides", "0037_aide_internal_comments_aide_raison_desactivation"),
        ("aides", "0038_alter_aide_last_published_at"),
        ("aides", "0039_aide_integration_method_aide_source"),
        ("aides", "0040_alter_aide_status"),
        ("aides", "0041_alter_aide_organisme"),
        ("aides", "0042_alter_aide_date_created_alter_aide_date_modified_and_more"),
    ]

    dependencies = [
        ("aides", "0035_alter_aide_beneficiaires_alter_aide_conditions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="raison_desactivation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Hors-sujet", "Hors-sujet"),
                    ("Clôturé", "Clôturé"),
                    ("En attente d'ouverture", "En attente d'ouverture"),
                    ("Erreur", "Erreur"),
                    ("Pas la bonne cible", "Pas la bonne cible"),
                ],
                default="",
                verbose_name="Raison de la désactivation",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="last_published_at",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="Date de publication"
            ),
        ),
        migrations.AddField(
            model_name="aide",
            name="integration_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Manuel", "Manuel"),
                    ("Scraping", "Scraping"),
                    ("Partenariat", "Partenariat"),
                    ("API", "API"),
                    ("Formulaire", "Formulaire"),
                    ("Import BDD", "Import BDD"),
                ],
                verbose_name="Mode de récolte de la donnée",
            ),
        ),
        migrations.AddField(
            model_name="aide",
            name="source",
            field=models.CharField(
                blank=True, verbose_name="Origine source de la donnée"
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="status",
            field=models.CharField(
                choices=[
                    ("0. À faire", "0. À faire"),
                    ("1. Scanné (au moins pertinence OK)", "1. Scanné"),
                    ("2. Éditorialisé", "2. Éditorialisé"),
                    ("2.2 Repasse nécessaire", "2.2 Repasse nécessaire"),
                    ("2.3 En attente", "2.3 En attente"),
                    ("3. OK Publication", "3. OK Publication"),
                    ("4. Désactivé", "4. Désactivé"),
                ],
                default="0. À faire",
                verbose_name="État",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="organisme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aides",
                to="aides.organisme",
                verbose_name="Organisme porteur",
            ),
        ),
        migrations.AddField(
            model_name="aide",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date d’intégration"
            ),
        ),
        migrations.AddField(
            model_name="aide",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AddField(
            model_name="aide",
            name="internal_comments",
            field=models.TextField(
                blank=True, default="", verbose_name="Commentaires internes"
            ),
        ),
    ]
