# Generated by Django 5.2.4 on 2025-08-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "aides",
            "0036_aide_date_created_aide_date_modified_and_more_squashed_0042_alter_aide_date_created_alter_aide_date_modified_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="conditions",
            field=models.TextField(blank=True, verbose_name="Conditions d’éligibilité"),
        ),
        migrations.AlterField(
            model_name="aide",
            name="contact",
            field=models.TextField(blank=True, verbose_name="Contacts"),
        ),
        migrations.AlterField(
            model_name="aide",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="aide",
            name="eligibilite_age",
            field=models.TextField(
                blank=True, verbose_name="Éligibilité\xa0: âge de l’exploitation"
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="eligibilite_cumulable",
            field=models.TextField(
                blank=True, verbose_name="Éligibilité\xa0: dispositif cumulable\xa0?"
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="etapes",
            field=models.TextField(blank=True, verbose_name="Étapes"),
        ),
        migrations.AlterField(
            model_name="aide",
            name="exemple_projet",
            field=models.TextField(
                blank=True, verbose_name="Exemple de projet ou d’application"
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="montant",
            field=models.TextField(
                blank=True, verbose_name="Montaux ou taux de l’aide"
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="participation_agriculteur",
            field=models.TextField(
                blank=True, verbose_name="Participation ou coût pour les bénéficiaires"
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="type_depense",
            field=models.TextField(
                blank=True, verbose_name="Types de dépenses éligibles"
            ),
        ),
    ]
