# Generated by Django 5.2.4 on 2025-08-05 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0043_alter_aide_conditions_alter_aide_contact_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="assigned_to",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigné à",
            ),
        ),
        migrations.AddField(
            model_name="aide",
            name="priority",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Priorité"),
        ),
    ]
