# Generated by Django 5.2.4 on 2025-08-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0044_aide_assigned_to_aide_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="date_target_publication",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date cible de publication"
            ),
        ),
    ]
