# Generated by Django 5.2.4 on 2025-08-14 14:31

from django.db import migrations, models


def change_statuses(apps, schema_editor):
    Aide = apps.get_model("aides", "Aide")
    Aide.objects.filter(status="0. À faire").update(status="01. À trier")
    Aide.objects.filter(status="1. Scanné (au moins pertinence OK)").update(
        status="03. Retenue - à structurer"
    )
    Aide.objects.filter(status="2. Éditorialisé").update(status="05. À valider")
    Aide.objects.filter(status="2.2 Repasse nécessaire").update(status="05. À valider")
    Aide.objects.filter(status="2.3 En attente").update(status="05. À valider")
    Aide.objects.filter(status="3. OK Publication").update(status="07. Publiée")
    Aide.objects.filter(status="4. Désactivé").update(status="98. Non retenue")


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0045_aide_date_target_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="status",
            field=models.CharField(
                choices=[
                    ("01. À trier", "01. À trier"),
                    ("02. En analyse", "02. En analyse"),
                    ("03. Retenue - à structurer", "03. Retenue - à structurer"),
                    ("04. À éditorialiser", "04. À éditorialiser"),
                    ("05. À valider", "05. À valider"),
                    ("06. À publier", "06. À publier"),
                    ("07. Publiée", "07. Publiée"),
                    ("08. À mettre à jour", "08. À mettre à jour"),
                    ("98. Non retenue", "98. Non retenue"),
                    ("99. Archivée", "99. Archivée"),
                ],
                default="01. À trier",
                verbose_name="État",
            ),
        ),
        migrations.RunPython(change_statuses),
    ]
