# Generated by Django 5.2.6 on 2025-09-19 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0046_alter_aide_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="cc_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="aides_cc",
                to=settings.AUTH_USER_MODEL,
                verbose_name="CC",
            ),
        ),
    ]
