# Generated by Django 5.2.6 on 2025-09-26 10:46

from django.db import migrations, models


def data_migration(apps, schema_editor):
    Aide = apps.get_model("aides", "Aide")
    statuses = {
        "01. À trier": "00",
        "02. En analyse": "00",
        "03. Retenue - à structurer": "20",
        "04. À éditorialiser": "20",
        "05. À valider": "30",
        "06. À publier": "40",
        "07. Publiée": "50",
        "08. À mettre à jour": "00",
        "98. Non retenue": "99",
        "99. Archivée": "99",
    }
    for old, new in statuses.items():
        Aide.objects.filter(status=old).update(status=new)


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0047_aide_cc_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="status",
            field=models.CharField(
                choices=[
                    ("00", "0. Backlog - À prioriser"),
                    ("10", "1. Priorisée - Scope à vérif"),
                    ("20", "2. Ok scope - À éditer"),
                    ("30", "3. Ok édito - À valider"),
                    ("40", "4. Publiée sous embargo"),
                    ("50", "5. Publiée"),
                    ("99", "6. Archivée"),
                ],
                default="00",
                verbose_name="État",
            ),
        ),
        migrations.RunPython(data_migration),
    ]
