# Generated by Django 5.2.6 on 2025-09-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0048_alter_aide_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aide",
            name="status",
            field=models.CharField(
                choices=[
                    ("00", "0. Backlog - À prioriser"),
                    ("10", "1. Priorisée - Scope à vérif"),
                    ("20", "2. Ok scope - À éditer"),
                    ("30", "3. Ok édito - À valider"),
                    ("31", "3.1 En attente validation métier"),
                    ("40", "4. Publiée sous embargo"),
                    ("50", "5. Publiée"),
                    ("99", "6. Archivée"),
                ],
                default="00",
                verbose_name="État",
            ),
        ),
    ]
