# Generated by Django 5.2.6 on 2025-09-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0049_alter_aide_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="aide",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.CASCADE,
                to="aides.aide",
                verbose_name="Dérivée de",
                related_name="children",
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="status",
            field=models.CharField(
                choices=[
                    ("00", "0. Backlog - À prioriser"),
                    ("10", "1. Priorisée - Scope à vérif"),
                    ("20", "2. Ok scope - À éditer"),
                    ("30", "3. Ok édito - À valider"),
                    ("31", "3.1 En attente validation métier"),
                    ("40", "4. Publiée sous embargo"),
                    ("41", "4.1 À décliner"),
                    ("50", "5. Publiée"),
                    ("99", "6. Archivée"),
                ],
                default="00",
                verbose_name="État",
            ),
        ),
        migrations.AddField(
            model_name="aide",
            name="is_derivable",
            field=models.BooleanField(default=False, verbose_name="Est déclinable"),
        ),
        migrations.AddField(
            model_name="aide",
            name="description_de_base",
            field=models.TextField(
                blank=True, verbose_name="Description de l’aide racine"
            ),
        ),
        migrations.AlterField(
            model_name="aide",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="children",
                to="aides.aide",
                verbose_name="Déclinée depuis",
            ),
        ),
    ]
