# Generated by Django 5.2.7 on 2025-10-06 10:52

from django.db import migrations


def data_migration(apps, *args):
    Aide = apps.get_model("aides", "Aide")
    derived = dict()
    prev_id = None
    prev_nom = ""
    prev_organisme_id = None
    for aide in Aide.objects.all().order_by("nom", "pk"):
        if (
            aide.organisme_id
            and aide.organisme_id == prev_organisme_id
            and aide.nom == prev_nom
        ):
            if prev_id not in derived:
                derived[prev_id] = []
            derived[prev_id].append(aide.pk)
        else:
            prev_id = aide.pk
            prev_nom = aide.nom
            prev_organisme_id = aide.organisme_id
    for parent_id, children in derived.items():
        Aide.objects.filter(pk=parent_id).update(status="41", is_derivable=True)
        Aide.objects.filter(pk__in=children).update(parent_id=parent_id)


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0050_aide_is_derivable"),
    ]

    operations = [
        migrations.RunPython(data_migration),
    ]
