# Generated by Django 5.2.7 on 2025-10-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0051_is_derivable_data_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="is_prioritaire",
            field=models.BooleanField(
                default=False, verbose_name="Thématique prioritaire"
            ),
        ),
        migrations.AddField(
            model_name="aide",
            name="demande_du_pourvoyeur",
            field=models.BooleanField(
                default=False,
                verbose_name="Demande de publication directement par le pourvoyeur d’aide",
            ),
        ),
        migrations.AddField(
            model_name="aide",
            name="enveloppe_globale",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Enveloppe globale allouée"
            ),
        ),
        migrations.AddField(
            model_name="aide",
            name="importance",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "1. Brulante - national"),
                    (8, "2. Nationale"),
                    (6, "3. Régionale"),
                    (4, "4. Locale"),
                    (0, "5. RAS, c'est calme"),
                ],
                default=0,
                verbose_name="Répond à une actualité brûlante",
            ),
        ),
        migrations.AddField(
            model_name="aide",
            name="is_meconnue",
            field=models.BooleanField(default=False, verbose_name="Aide méconnue"),
        ),
        migrations.AddField(
            model_name="aide",
            name="is_filiere_sous_representee",
            field=models.BooleanField(
                default=False, verbose_name="Filière sous-représentée"
            ),
        ),
        migrations.AddField(
            model_name="aide",
            name="taille_cible_potentielle",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Nombre d'agriculteurs potentiellement touchés",
            ),
        ),
        migrations.AddField(
            model_name="aide",
            name="urgence",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (10, "1. Très urgent ou dure longtemps"),
                    (5, "2. Moyen urgent, ou dure quelques mois"),
                    (2, "3. Pas urgent ou dure que quelques semaines"),
                ],
                default=2,
                verbose_name="Degré d’urgence ou durée du dispositif",
            ),
        ),
        migrations.AddField(
            model_name="organisme",
            name="is_masa",
            field=models.BooleanField(default=False, verbose_name="Made in MASA"),
        ),
        migrations.AddField(
            model_name="type",
            name="score_priorite_aides",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
