# Generated by Django 5.2.7 on 2025-10-06 11:08

from django.db import migrations

from ..models import Aide


def data_migration(*args):
    for aide in Aide.objects.all():
        aide.compute_priority()
        aide.save()


class Migration(migrations.Migration):
    dependencies = [
        ("aides", "0052_aide_compute_priority"),
    ]

    operations = [
        migrations.RunPython(data_migration),
    ]
