# Generated by Django 5.2.1 on 2025-05-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date et heure"
                    ),
                ),
                (
                    "information_quality",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Pas du tout"),
                            (25, "Un peu"),
                            (50, "Moyen"),
                            (75, "Beaucoup"),
                            (100, "Parfait !"),
                        ],
                        verbose_name="L’information qui vous a été donnée est-elle qualitative selon vous ?",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        verbose_name="Quelles sont les améliorations à effectuer selon vous ?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Retour utilisateur",
                "verbose_name_plural": "Retours utilisateurs",
            },
        ),
        migrations.CreateModel(
            name="UserNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date et heure"
                    ),
                ),
                (
                    "usefulness",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Pas du tout"),
                            (25, "Un peu"),
                            (50, "Moyen"),
                            (75, "Beaucoup"),
                            (100, "Parfait !"),
                        ],
                        verbose_name="Cette page vous a-t-elle été utile ?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appréciation",
                "verbose_name_plural": "Appréciations",
            },
        ),
    ]
