# Generated by Django 5.2.1 on 2025-05-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="information_quality",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Pas du tout"),
                    (25, "Un peu"),
                    (50, "Moyen"),
                    (75, "Beaucoup"),
                    (100, "Parfait !"),
                ],
                verbose_name="Selon vous, l’information qui vous a été donnée est-elle qualitative\xa0?",
            ),
        ),
    ]
