# Generated by Django 5.1.7 on 2025-03-27 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filiere",
            fields=[
                (
                    "external_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField()),
                ("position", models.IntegerField(default=0, unique=True)),
                ("code_naf", models.CharField(blank=True, max_length=10)),
            ],
            options={
                "verbose_name": "Filière",
                "verbose_name_plural": "Filières",
                "ordering": ("position",),
            },
        ),
        migrations.CreateModel(
            name="GroupementProducteurs",
            fields=[
                (
                    "external_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField()),
                ("libelle", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Groupement de producteurs",
                "verbose_name_plural": "Groupement de producteurs",
                "ordering": ("-nom",),
            },
        ),
        migrations.CreateModel(
            name="SousFiliere",
            fields=[
                (
                    "external_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField()),
                (
                    "filiere",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agri.filiere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous-filière",
                "verbose_name_plural": "Sous-filières",
            },
        ),
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "external_id",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField()),
                (
                    "sous_filiere",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agri.sousfiliere",
                    ),
                ),
            ],
            options={
                "verbose_name": "Détail de production",
                "verbose_name_plural": "Détails de production",
            },
        ),
    ]
