# Generated by Django 5.2.1 on 2025-05-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agri", "0001_initial_another_one"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="sent_from_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
