# Generated by Django 5.1.7 on 2025-03-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agri", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filiere",
            name="nom",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="groupementproducteurs",
            name="nom",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="production",
            name="nom",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="sousfiliere",
            name="nom",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
