# Generated by Django 5.2.1 on 2025-05-16 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agri", "0002_feedback_sent_from_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "Feedback sur les thèmes et sujets",
                "verbose_name_plural": "Feedbacks sur les thèmes et sujets",
            },
        ),
    ]
