# Generated by Django 5.2 on 2025-04-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agri", "0002_alter_filiere_nom_alter_groupementproducteurs_nom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupementproducteurs",
            name="is_real",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(libelle="", then=False),
                    default=True,
                    output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
            ),
        ),
    ]
