# Generated by Django 5.2 on 2025-04-14 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agri", "0003_groupementproducteurs_is_real"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupementproducteurs",
            options={
                "ordering": ("-is_real", "nom"),
                "verbose_name": "Groupement de producteurs",
                "verbose_name_plural": "Groupement de producteurs",
            },
        ),
    ]
