# Generated by Django 5.2.6 on 2025-09-16 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pac", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicateurresultat",
            name="denominateur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pac.indicateurcontexte",
            ),
        ),
        migrations.AlterField(
            model_name="indicateurresultat",
            name="moment_collecte",
            field=models.CharField(
                choices=[("Acompte", "Acompte"), ("Solde", "Solde")]
            ),
        ),
        migrations.AlterField(
            model_name="indicateurresultat",
            name="type_calcul",
            field=models.CharField(choices=[("Ratio", "Ratio"), ("Somme", "Somme")]),
        ),
    ]
