# Generated by Django 5.2.6 on 2025-09-16 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pac", "0002_indicateurresultat_denominateur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervention",
            name="secteur",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="pac.secteur"
            ),
        ),
    ]
