# Generated by Django 5.2.6 on 2025-09-16 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pac", "0003_alter_intervention_secteur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervention",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pac.typeintervention",
            ),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="type_zone_ichn",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MO", "Zones de montagne"),
                    ("CN", "ZSCN - zone à contraintes naturelles importantes"),
                    ("CS", "ZSCS - Zones à contraintes spécifiques"),
                ],
            ),
        ),
    ]
