# Generated by Django 5.2.4 on 2025-07-09 15:01

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Read",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obj", models.CharField()),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Write",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obj", models.CharField()),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="read",
            trigger=pgtrigger.compiler.Trigger(
                name="delete_expired",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="DELETE FROM admin_concurrency_read WHERE last_seen < NOW() - INTERVAL '1 minute'; RETURN NEW;",
                    hash="f270d36a64a5a7a9674ee57b72671e44f7c374b4",
                    level="STATEMENT",
                    operation="INSERT OR UPDATE",
                    pgid="pgtrigger_delete_expired_5ce5f",
                    table="admin_concurrency_read",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AlterUniqueTogether(
            name="write",
            unique_together={("obj", "user")},
        ),
    ]
