# Generated by Django 5.2.7 on 2025-10-14 09:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("aides", "0053_aide_compute_priority_data_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackOnThemesAndSujets",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, verbose_name="Navigateur web"),
                ),
                ("is_spam", models.BooleanField(default=False, verbose_name="Spam")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date"),
                ),
                (
                    "sent_from_url",
                    models.URLField(
                        blank=True, max_length=2000, verbose_name="URL concernée"
                    ),
                ),
                ("message", models.TextField()),
            ],
            options={
                "verbose_name": "Retour utilisateurice sur les thèmes et sujets",
                "verbose_name_plural": "Retours utilisateurices sur les thèmes et sujets",
            },
        ),
        migrations.CreateModel(
            name="FeedbackOnAides",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, verbose_name="Navigateur web"),
                ),
                ("is_spam", models.BooleanField(default=False, verbose_name="Spam")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date"),
                ),
                (
                    "sent_from_url",
                    models.URLField(
                        blank=True, max_length=2000, verbose_name="URL concernée"
                    ),
                ),
                (
                    "usefulness",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Pas du tout"),
                            (25, "Un peu"),
                            (50, "Moyen"),
                            (75, "Beaucoup"),
                            (100, "Parfait !"),
                        ],
                        verbose_name="Cette page vous a-t-elle été utile\xa0?",
                    ),
                ),
                (
                    "information_quality",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Pas du tout"),
                            (25, "Un peu"),
                            (50, "Moyen"),
                            (75, "Beaucoup"),
                            (100, "Parfait !"),
                        ],
                        null=True,
                        verbose_name="Selon vous, l’information qui vous a été donnée est-elle qualitative\xa0?",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        verbose_name="Quelles sont les améliorations à effectuer selon vous\xa0?",
                    ),
                ),
                (
                    "aide",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aides.aide",
                        verbose_name="Aide concernée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retour utilisateurice sur les aides",
                "verbose_name_plural": "Retours utilisateurices sur les aides",
            },
        ),
    ]
